print("What is your name?")
name = str(input())
print("\n")
print("How old are you (in years)?")
age = int(input())
print("\n")
print("How tall are you (in meters)?")
height = float(input())
print("\n")
print("How much do you weight(in kilograms)?")
weight = float(input())
print("\n")
print("\n")
bmi = weight /(height**2)
print(name,"you are", age,"old and your bmi is",bmi )