print("Please enter the number of lives:")
lives =  input(int())
print("\n")
print("Please enter the energy level:")
energy = input(int())
print("\n")
print("Please enter the shield level:")
shield = input(int())
print("\n")
print("Health has been set")
print("\n")
print("Lives =",lives)
print("Energy =",energy)
print("Shield =",shield)